%YAML 1.1
---
resolve: commits
owner: jimschubert
repo: delete-artifacts-action
groupings:
  - name: Features
    patterns: ['(?i)^.*?(feat|new|initial|support|introduce)\b.*?:']
  - name: Bug Fixes
    patterns: ['(?i)^.*?(fix|bug)\b.*?:', '(?i).*fixes$']
  - name: Documentation
    patterns: ['(?i)^.*?docs?(\(.+\))?\b.*?:']
  - name: Dependency Updates
    patterns: ['(?i)^.*?(build|deps|upgrade|update)(\(.+\))?\b.*?:']
  - name: Other Changes
    patterns: ['.*']
exclude:
  - '^(?i)wip\b'
  - '^(?i)help\b'
  - '^(?i)trying\b'
  - '^(?i)workflow\b'
  - '^(?i)update readme\b'
  - '^(?i)test\b'
  - '^(?i)style\b'
  - '^(?i)chore\b'
sort: asc
max_commits: 250
local: false